//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentoRide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_acc
    {
        public int id { get; set; }
        public string customer_firstname { get; set; }
        public string customer_middlename { get; set; }
        public string customer_lastname { get; set; }
        public string customer_namesuffix { get; set; }
        public int customer_contact { get; set; }
        public string customer_email { get; set; }
        public string customer_password { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    }
}
