//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RenttoRideFP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_reg
    {
        public int car_id { get; set; }
        public string car_plateno { get; set; }
        public string car_brand { get; set; }
        public string car_model { get; set; }
        public string car_color { get; set; }
        public int car_capacity { get; set; }
        public bool car_availability { get; set; }
    }
}
